### ISSUE TITLE
Warning in eslint v5

### ISSUE THREAD

**Issue by binkpitch** [storylog/eslint-config-storylog#5]
Got this warning after upgrading to eslint v5
<img width="1098" alt="screen shot 2561-12-20 at 13 15 55" src="https://user-images.githubusercontent.com/20456165/50267459-dd206900-0459-11e9-92a0-75edebe46ad9.png">

**Comment by nsmag** [comment]
It's not been updated for a long time.
I think we can revise the whole config to suit our team.

**Comment by binkpitch** [comment]
Do you think eslint config should be separated between front-end and back-end?

**Comment by nsmag** [comment]
I think backend can use frontend config.
I cannot think of a use-case that we really need many specific configs.

**Comment by nsmag** [comment]
@binkpitch 
What's the minimum requirement of this?
What project can I reference for the config?

**Comment by binkpitch** [comment]
I think `fictionlog-web` can be a good reference. See `.eslintrc`.
